task: sa
cuda_id: 0
seed: 42

wandb_dir: /path/to/repo
wandb_prj: project
save_path: ./result/project/abmil_gat_attn-MLE_YEAR
save_prediction: True
eval_training_loader_per_epoch: False
ckpt_for_eval: last # last / best

# ---------------------------------------------
# [UPDATE] DATA LOADING FOR ZERO-SHOT
# ---------------------------------------------
zero_shot_mode: True # Cờ mới để báo cho code biết đây là test zero-shot
dataset_name: ['thym']  # ['uvm', 'chol', 'acc', 'dlbc', 'meso', 'ov', 'paad', 'pcpg', 'tgct', 'ucs', 'thym', 'prad', 'thca']
path_patch: A:/CROPKT_DATASET/{dataset}/TCGA_{dataset}
path_coord: null
path_table: A:/CROPKT_DATASET/{dataset}/CSV/tcga_{dataset}_survival.csv
data_mode: patch
path_cluster: null
feat_format: h5
time_format: interval 
time_bins: 32 
time_event_max: 11680 
data_split_path: A:/CROPKT_DATASET/{dataset}/CSV/splits_{fold}.csv
data_split_fold: [0]
# ---------------------------------------------

# network architecture
arch: DeepMIL 
init_wt: False
net_output_converter: sigmoid 

# DeepMIL setttings
deepmil_network: ABMIL
deepmil_dim_in: 1536 
deepmil_dim_emb: 512
deepmil_num_cls: 32 
deepmil_dim_attn: 384
deepmil_num_feat_proj_layers: 0
deepmil_drop_rate: 0.25
deepmil_pooling: gated_attention 

# training loss
loss_type: SurvMLE 
loss_survmle_weight: 1.0
loss_survmle_alpha: 0.5

# evaluator
evaluator: NLL 
evaluator_backend: default

# optimizer
opt_name: adamW
opt_lr: 0.0001
opt_weight_decay: 0.00001

# training
epochs: 20
batch_size: 1
bp_every_batch: 16 
num_workers: 4

# LR Scheduler
lrs: True
lrs_name: cosine
lrs_warmup_steps: -1
lrs_warmup_epochs: 1

# Early Stopping
es: False
es_patience: 20
es_warmup: 0
es_verbose: True
es_start_epoch: 0
monitor_metrics: loss 

# ---------------------------------------------
# ZERO-SHOT TESTING SETTINGS
# ---------------------------------------------
test: True
test_wandb_prj: Project-Zero-Transfer 
test_save_path: A:/CROPKT/test_results_1/zero_transfer 
test_split: test 
test_source_dataset_name: ['gbmlgg', 'hnsc', 'kipan', 'lihc', 'lung', 'sarc', 'skcm', 'stes', 'ucec'] # Các model pre-trained từ bệnh này
test_source_data_split_fold: [0, 1, 2, 3, 4]
test_load_ckpt_path: A:/CROPKT/saved_experts/{source_dataset}_expert-data_tcga_{source_dataset}-fold_{source_fold}
test_save_wsi_representation: True
test_save_wsi_representation_path: A:/CROPKT/transfer_features_1/target_{dataset}/source_{source_dataset}-fold_{source_fold}